# Generated by Django 5.0.7 on 2024-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(default=None, help_text='Ex:MPT0001', max_length=255, unique=True, verbose_name='transaction number'),
        ),
    ]
