# Generated by Django 6.0.2 on 2026-03-07 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('payment', '0002_update_transaction_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_transac_014686_idx',
            old_name='payment_tra_transac_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_externa_18ff24_idx',
            old_name='payment_tra_externa_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_user_id_b01674_idx',
            old_name='payment_tra_user_id_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.enrollment', verbose_name='inscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Carte de crédit'), ('moncash', 'MonCash'), ('natcash', 'NatCash'), ('kashpaw', 'Kashpaw'), ('other', 'Autre')], default='credit_card', max_length=20, verbose_name='méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Ex: 1000.00', max_digits=10, verbose_name='prix'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, help_text='Ex: KOULKY000001', max_length=255, null=True, unique=True, verbose_name='numéro de transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='payment_pay_created_c2327c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payment_pay_user_id_e01707_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['enrollment'], name='payment_pay_enrollm_d8193d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='payment_tra_created_7fbad7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payment_tra_status_373de7_idx'),
        ),
    ]
