# Generated by Django 6.0.3 on 2026-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='provider_transaction_id',
            field=models.CharField(blank=True, help_text='Numéro de transaction réel du télco (MonCash/NatCash), capturé à la confirmation', max_length=255, null=True, verbose_name='ID transaction MonCash/NatCash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_transaction_id',
            field=models.CharField(blank=True, help_text="ID d'ordre du fournisseur de paiement (PlopPlop / Stripe)", max_length=255, null=True, verbose_name='ID transaction externe'),
        ),
    ]
