# Generated by Django 6.0.2 on 2026-03-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KouLakay', max_length=100, verbose_name='Nom du site')),
                ('tagline', models.CharField(blank=True, default="Rendre l'éducation de qualité accessible à tous.", max_length=255, verbose_name='Slogan')),
                ('address', models.CharField(blank=True, default='Port-au-Prince, Haïti', max_length=255, verbose_name='Adresse')),
                ('phone_1', models.CharField(blank=True, default='+509 3000 0000', max_length=30, verbose_name='Téléphone principal')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, default='info@koulakay.ht', max_length=254, verbose_name='Email de contact')),
                ('email_support', models.EmailField(blank=True, max_length=254, verbose_name='Email support')),
                ('map_embed_url', models.TextField(blank=True, help_text="Copiez l'URL src de l'iframe depuis Google Maps → Partager → Intégrer une carte", verbose_name="URL d'intégration Google Maps")),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('footer_text', models.CharField(blank=True, default='Conçu avec ❤️ pour Haïti', max_length=255, verbose_name='Texte pied de page')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
