# Generated by Django 6.0.3 on 2026-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('image', models.ImageField(help_text='Recommandé : 1920×800 px minimum', upload_to='hero_slides/', verbose_name='Image')),
                ('cta_label', models.CharField(blank=True, default='Explorer les cours', max_length=60, verbose_name='Texte du bouton CTA')),
                ('cta_url', models.CharField(blank=True, default='/fr/courses/courses/', max_length=200, verbose_name='URL du bouton CTA')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide hero',
                'verbose_name_plural': 'Slides hero',
                'ordering': ['order'],
            },
        ),
    ]
