# Generated by Django 6.0.3 on 2026-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_hero_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)'), ('CAD', 'Dollar canadien (CAD)'), ('GBP', 'Livre sterling (GBP)'), ('HTG', 'Gourde haïtienne (HTG)')], default='USD', help_text="Devise utilisée pour afficher les prix sur toutes les pages (sauf la page de paiement qui affiche aussi l'équivalent HTG).", max_length=3, verbose_name="Devise d'affichage"),
        ),
    ]
