# Generated by Django 6.0.3 on 2026-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_currency_to_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='cta_label_en',
            field=models.CharField(blank=True, default='Explorer les cours', max_length=60, null=True, verbose_name='Texte du bouton CTA'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_label_es',
            field=models.CharField(blank=True, default='Explorer les cours', max_length=60, null=True, verbose_name='Texte du bouton CTA'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_label_fr',
            field=models.CharField(blank=True, default='Explorer les cours', max_length=60, null=True, verbose_name='Texte du bouton CTA'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_label_ht',
            field=models.CharField(blank=True, default='Explorer les cours', max_length=60, null=True, verbose_name='Texte du bouton CTA'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_ht',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_es',
            field=models.CharField(max_length=120, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ht',
            field=models.CharField(max_length=120, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_en',
            field=models.CharField(blank=True, default='Conçu avec ❤️ pour Haïti', max_length=255, null=True, verbose_name='Texte pied de page'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_es',
            field=models.CharField(blank=True, default='Conçu avec ❤️ pour Haïti', max_length=255, null=True, verbose_name='Texte pied de page'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_fr',
            field=models.CharField(blank=True, default='Conçu avec ❤️ pour Haïti', max_length=255, null=True, verbose_name='Texte pied de page'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_ht',
            field=models.CharField(blank=True, default='Conçu avec ❤️ pour Haïti', max_length=255, null=True, verbose_name='Texte pied de page'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline_en',
            field=models.CharField(blank=True, default="Rendre l'éducation de qualité accessible à tous.", max_length=255, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline_es',
            field=models.CharField(blank=True, default="Rendre l'éducation de qualité accessible à tous.", max_length=255, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline_fr',
            field=models.CharField(blank=True, default="Rendre l'éducation de qualité accessible à tous.", max_length=255, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline_ht',
            field=models.CharField(blank=True, default="Rendre l'éducation de qualité accessible à tous.", max_length=255, null=True, verbose_name='Slogan'),
        ),
    ]
