# Generated by Django 6.0.3 on 2026-04-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_heroslide_cta_label_en_heroslide_cta_label_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_partenaire',
            field=models.ImageField(blank=True, help_text='Logo du partenaire (ex: Exam Haiti) affiché à côté du logo principal. Format PNG ou JPEG, hauteur recommandée : 80px minimum.', upload_to='logos/', verbose_name='Logo partenaire'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo_principal',
            field=models.ImageField(blank=True, help_text='Logo KouLakay affiché dans le header et les pages de connexion. Format PNG recommandé, fond transparent.', upload_to='logos/', verbose_name='Logo principal'),
        ),
    ]
