# Generated by Django 6.0.3 on 2026-05-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_seed_default_hero_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'À propos'), ('contact', 'Contact')], db_index=True, help_text='Page sur laquelle ce slide apparaît.', max_length=20, verbose_name='Page')),
                ('image', models.ImageField(help_text='Recommandé : 1920×800 px minimum', upload_to='page_slides/', verbose_name='Image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide de page',
                'verbose_name_plural': 'Slides de pages',
                'ordering': ['page', 'order'],
            },
        ),
    ]
