# Generated by Django 6.0.3 on 2026-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_seed_page_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='payment_video_moncash_file',
            field=models.FileField(blank=True, help_text="Alternative si vous n'avez pas de lien. ⚠️ Un fichier uploadé peut être perdu lors d'une mise à jour du site — préférez le lien ci-dessus.", upload_to='demo_videos/', verbose_name='Vidéo MonCash — fichier (option)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='payment_video_moncash_url',
            field=models.URLField(blank=True, help_text="Lien YouTube ou Vimeo (non-listé) montrant comment payer par MonCash. Recommandé : contrairement à un fichier uploadé, le lien n'est jamais perdu.", verbose_name='Vidéo MonCash — lien (recommandé)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='payment_video_natcash_file',
            field=models.FileField(blank=True, help_text="Alternative si vous n'avez pas de lien. ⚠️ Préférez le lien ci-dessus.", upload_to='demo_videos/', verbose_name='Vidéo NatCash — fichier (option)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='payment_video_natcash_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo (non-listé) montrant comment payer par NatCash.', verbose_name='Vidéo NatCash — lien (recommandé)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_message',
            field=models.CharField(blank=True, default="Bonjour KouLakay, j'ai une question.", help_text='Texte inséré automatiquement dans la conversation quand on clique sur le bouton.', max_length=255, verbose_name='Message WhatsApp pré-rempli'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Format international, ex : +509 3000 0000. Affiché en bouton flottant sur tout le site. Laisser vide pour masquer le bouton.', max_length=30, verbose_name='Numéro WhatsApp'),
        ),
    ]
