# Generated by Django 6.0.2 on 2026-03-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thinkific_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
