# Generated by Django 6.0.3 on 2026-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(db_index=True, verbose_name='Thinkific course ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('ht', 'Kreyòl Ayisyen')], max_length=5, verbose_name='Langue')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom du cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Traduction de cours',
                'verbose_name_plural': 'Traductions de cours',
                'unique_together': {('course_id', 'language')},
            },
        ),
    ]
