# Generated by Django 5.0.7 on 2024-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='thinkific_user_id',
            field=models.IntegerField(default=1, verbose_name='thinkific user id'),
            preserve_default=False,
        ),
    ]
