# Generated by Django 6.0.3 on 2026-05-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursegroup_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePriceDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True, verbose_name='ID Thinkific')),
                ('course_name_cache', models.CharField(blank=True, max_length=255, verbose_name='Nom du cours')),
                ('display_currency', models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)'), ('CAD', 'Dollar canadien (CAD)'), ('GBP', 'Livre sterling (GBP)'), ('HTG', 'Gourde haïtienne (HTG)')], default='USD', max_length=3, verbose_name="Devise d'affichage")),
            ],
            options={
                'verbose_name': "Devise d'affichage (cours)",
                'verbose_name_plural': "Devises d'affichage (cours)",
                'ordering': ['course_name_cache'],
            },
        ),
    ]
